##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2015                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

##########################################################################
#                                                                        #
# Define variables from configure.                                       #
# These variables may be redefined later.                                #
#                                                                        #
##########################################################################

#######################
# Working directories #
#######################

FRAMAC_TOP_SRCDIR 	?= /home/pascal/tis-interpreter

######################
# Installation paths #
######################

CYGPATH         ?=

DESTDIR 	?=
prefix		?=/home/pascal/tis-interpreter/tis-interpreter/tis-interpreter
exec_prefix	?=${prefix}
datarootdir     ?=${prefix}/share
datadir         ?=${datarootdir}
BINDIR		?="$(DESTDIR)${exec_prefix}/bin"
LIBDIR		?="$(DESTDIR)${exec_prefix}/lib"
DATADIR		?="$(DESTDIR)${prefix}/share"
MANDIR		?="$(DESTDIR)${datarootdir}/man"

FRAMAC_LIBDIR	?=$(LIBDIR)/frama-c
FRAMAC_PLUGINDIR ?=$(FRAMAC_LIBDIR)/plugins
FRAMAC_DATADIR 	?=$(DATADIR)/frama-c
EMACS_DATADIR	?=$(DATADIR)/emacs/site-lisp
FRAMAC_DEFAULT_CPP ?=gcc -E -C -I.
FRAMAC_GNU_CPP ?=true
DEFAULT_CPP_KEEP_COMMENTS?=true
CC =gcc

###############
# Ocaml stuff #
###############

# compilers and others executables
OCAMLC  	?=ocamlc.opt
OCAMLOPT	?=ocamlopt.opt
OCAMLDEP	?=ocamldep.opt -slash
OCAMLLEX	?=ocamllex.opt
OCAMLYACC	?=ocamlyacc
OCAMLMKTOP	?=ocamlmktop
OCAMLDOC	?=ocamldoc.opt
OCAMLCP		?=ocamlcp

# others ocaml stuffs

# either -annot or -dtypes
OCAML_ANNOT_OPTION ?=-bin-annot
# ocaml stdlib path
OCAMLLIB	?=/home/pascal/tis-home/opam/4.02.1/lib/ocaml
# either opt or byte
OCAMLBEST	?=opt
OCAMLVERSION 	?=4.02.1
NATIVE_DYNLINK  ?=yes
USABLE_NATIVE_DYNLINK ?=yes
NATIVE_THREADS	?=yes
OCAMLWIN32	?=no
PTESTSBEST      ?=opt

#############
# Libraries #
#############

# ocamlgraph
OCAMLGRAPH_INCLUDE?=-I /home/pascal/tis-home/opam/4.02.1/lib/ocamlgraph # ocamlgraph compilation directive
OCAMLGRAPH_LOCAL  ?=
OCAMLGRAPH_HOME   ?=/home/pascal/tis-home/opam/4.02.1/lib/ocamlgraph

# lablgtk
HAS_LABLGTK	?=yes
HAS_LABLGTK_CUSTOM_MODEL ?=yes
LABLGTK_PATH ?=/home/pascal/tis-home/opam/4.02.1/lib/lablgtk2

# lablgtksourceview
HAS_GTKSOURCEVIEW ?=yes

# lablgnomecanvas
HAS_GNOMECANVAS	?=yes

# zarith
HAS_ZARITH	?=yes
ZARITH_PATH	?=/home/pascal/tis-home/opam/4.02.1/lib/zarith

# apron
HAS_APRON	?=no
APRON_PATH	?=

##########################
# Miscellaneous commands #
##########################

OTAGS		?=
DOT		?=dot
HAS_DOT		?=yes

HEADACHE 	?= headache -c $(FRAMAC_SRC)/headers/headache_config.txt

###########################
# Miscellaneous variables #
###########################

VERBOSEMAKE	?=no
LOCAL_MACHDEP	?=no
EXE		?=

# Required by Cil
UNDERSCORE_NAME ?=
HAVE_BUILTIN_VA_LIST ?=
THREAD_IS_KEYWORD ?=

##########################
# Variables for plug-ins #
##########################

EXTERNAL_PLUGINS ?= 

# Integrated plugins
ENABLE_CALLGRAPH                  ?=partial
ENABLE_CONSTANT_PROPAGATION       ?=yes
ENABLE_FROM_ANALYSIS              ?=no
ENABLE_GUI	                  ?=no
ENABLE_IMPACT	                  ?=no
ENABLE_INOUT	                  ?=no
ENABLE_METRICS	                  ?=no
ENABLE_OCCURRENCE                 ?=no
ENABLE_PDG	                  ?=no
ENABLE_POSTDOMINATORS             ?=no
ENABLE_RTEGEN                     ?=yes
ENABLE_SCOPE	                  ?=no
ENABLE_SLICING	                  ?=no
ENABLE_SPARECODE                  ?=no
ENABLE_USERS	                  ?=yes
ENABLE_VALUE_ANALYSIS             ?=partial

DYNAMIC_CALLGRAPH                 ?=no
DYNAMIC_CONSTANT_PROPAGATION      ?=no
DYNAMIC_FROM_ANALYSIS             ?=no
#DYNAMIC_GUI: never dynamic
DYNAMIC_IMPACT	                  ?=no
DYNAMIC_INOUT                     ?=no
DYNAMIC_METRICS                   ?=no
DYNAMIC_OCCURRENCE                ?=no
DYNAMIC_PDG                       ?=no
#DYNAMIC_POSTDOMINATORS: never dynamic
#DYNAMIC_RTEGEN: never dynamic
DYNAMIC_SCOPE                     ?=no
DYNAMIC_SLICING                   ?=no
DYNAMIC_SPARECODE                 ?=no
DYNAMIC_USERS                     ?=no
DYNAMIC_VALUE_ANALYSIS            ?=no

##########################################################################
# Local Variables:
# mode: makefile
# End:
